### ISSUE TITLE
Unable to load ng-annotate because of Path Error

### ISSUE THREAD

**Issue by panbhatt** [MichalZalecki/angular-lazyload-webpack#1]
Hi Team,
   There is an error while loading ng-annotate. The reason is because of extra character present in the Root directory path at webpack.config.js 
The fragment should be like this. 

  resolve: {
    root: __dirname + '/src',
  },

instead of 
  resolve: {
    root: __dirname + '/src/',
  },

Tested on : Windows 8 / Node 12.

Effect: This won't allow the sample message all/new to work and webpack is throwing an error while building up the package. 
I already solved it and informed how to use $scope and other services at [https://github.com/panbhatt/angular-lazyload-webpack](https://github.com/panbhatt/angular-lazyload-webpack)

**Comment by MichalZalecki** [comment]
I'm using node 5.x and linux. I didn't encounter such problems, I'm glad you figured that out.
