### ISSUE TITLE
Do you know how to concat all bundle file to one?

### ISSUE THREAD

**Issue by mqliutie** [MichalZalecki/angular-lazyload-webpack#2]
I have cloned your project and `npm i  && npm run build`.

In build folder there are  list of files : 

```
bundle.js
1.bundle.js
2.bundle.js
3.bundle.js
4.bundle.js
5.bundle.js
```

I think there have many files, can i merge them into one file?

In previous projects `index.html` only have two script tags one is `app.[hash].js` another is `lib.[hash].js`

Although there `index.html` also has a script tag ,but there also have many files(1.bundle.js etc)

If can merge them I think it's excellent.

Thanks for your help!

**Comment by MichalZalecki** [comment]
I think you're missing the point. We lazyload things to not load everything at once. It's on purpose. Here's the explanation: http://michalzalecki.com/lazy-load-angularjs-with-webpack/
