### ISSUE TITLE
"../bootstrap.js" is not in the SourceMap."

### ISSUE THREAD

**Issue by aaronyoung001** [MichalZalecki/angular-lazyload-webpack#3]
hi michal,
Thank you for your Share.But i have met some problems when I run the example code.It shows **“Module build failed: Error: "../bootstrap.js" is not in the SourceMap."**
I didn't change your code,what I did was just npm install and run it.
But when I use 'webpack ' directly in command line ,it runs well.
My Os is Mac OsX,and Node is 0.10.26(I have changed my Nodejs in different version,include 6.0.0 and 5.2.0).

**Comment by mdopieralski** [comment]
#4

**Comment by motin** [comment]
This is due to https://github.com/huston007/ng-annotate-loader/issues/20
Update package.json dev dep to "ng-annotate-loader": "0.1.1" to resolve this.

**Comment by mdopieralski** [comment]
Hi @motin, I've fixed it couple weeks ago. It's currently in pull requests, hope that @MichalZalecki will accept it soon :-)

**Comment by MichalZalecki** [comment]
Accepted, thanks for the input :white_check_mark:
